// Bundles context/voice-skill.txt and context/published/* into lib/voice-profile.js, so the
// edge function carries Meera's profile without reading files at runtime.
// Run after editing anything in context/ (npm test fails if you forget).
import { readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export function buildContextModule() {
  const voice = readFileSync('context/voice-skill.txt', 'utf8').trim();
  const published = existsSync('context/published')
    ? readdirSync('context/published').filter((f) => /\.(txt|md)$/i.test(f)).sort()
        .map((name) => ({ name, text: readFileSync(`context/published/${name}`, 'utf8').trim() }))
        .filter((p) => p.text)
    : [];
  return `// GENERATED by scripts/build-context.js from context/. Do not edit by hand.
export const VOICE = ${JSON.stringify(voice)};
export const PUBLISHED = ${JSON.stringify(published, null, 2)};
`;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync('lib/voice-profile.js', buildContextModule());
  console.log('wrote lib/voice-profile.js');
}
